#include "os_core.h"

String os_key_names[] = {
    str_lit("Nil"),
    str_lit("A"),
    str_lit("B"),
    str_lit("C"),
    str_lit("D"),
    str_lit("E"),
    str_lit("F"),
    str_lit("G"),
    str_lit("H"),
    str_lit("I"),
    str_lit("J"),
    str_lit("K"),
    str_lit("L"),
    str_lit("M"),
    str_lit("N"),
    str_lit("O"),
    str_lit("P"),
    str_lit("Q"),
    str_lit("R"),
    str_lit("S"),
    str_lit("T"),
    str_lit("U"),
    str_lit("V"),
    str_lit("W"),
    str_lit("X"),
    str_lit("Y"),
    str_lit("Z"),

    str_lit("0"),
    str_lit("1"),
    str_lit("2"),
    str_lit("3"),
    str_lit("4"),
    str_lit("5"),
    str_lit("6"),
    str_lit("7"),
    str_lit("8"),
    str_lit("9"),

    str_lit("Space"),
    str_lit("Comma"),
    str_lit("Period"),
    str_lit("Quote"),

    str_lit("OpenBracket"),
    str_lit("CloseBracket"),
    str_lit("SemiColon"),
    str_lit("Slash"),
    str_lit("BackSlash"),
    str_lit("Minus"),
    str_lit("Plus"),
    str_lit("Tab"),
    str_lit("Tick"),
    str_lit("Escape"),
    str_lit("Enter"),
    str_lit("Backspace"),
    str_lit("Delete"),
    str_lit("Left"),
    str_lit("Right"),
    str_lit("Up"),
    str_lit("Down"),
    str_lit("Home"),
    str_lit("End"),
    str_lit("PageUp"),
    str_lit("PageDown"),
    
    str_lit("F1"),
    str_lit("F2"),
    str_lit("F3"),
    str_lit("F4"),
    str_lit("F5"),
    str_lit("F6"),
    str_lit("F7"),
    str_lit("F8"),
    str_lit("F9"),
    str_lit("F10"),
    str_lit("F11"),
    str_lit("F12"),

    str_lit("Super"),

    str_lit("LeftMouse"),
    str_lit("MiddleMouse"),
    str_lit("RightMouse"),
};
